### ISSUE TITLE
Use hackerwebapp.com domain for the app?

### ISSUE THREAD

**Issue by longouyang** [cheeaun/hackerweb#49]
It'd be nice if the actual web app lived on hackerwebapp.com

**Comment by cheeaun** [comment]
Finally! Honestly I've been thinking of having a domain for the app itself for a *long time*, but haven't seen anyone complaining about it :smirk: I'm not going to *replace* the current landing page with the app since that's going to be confusing and abrupt, but I've been waiting patiently to register a new domain when [.app](http://icannwiki.com/.app) is available :heart_eyes:

**Comment by longouyang** [comment]
In the meantime, would it be easy to host the app in a subdirectory of hackerwebapp.com, say, `hackerwebapp.com/app/`?

**Comment by berbaquero** [comment]
Wait, am I missing something? What about http://app.hackerwebapp.com/? Just tried it — it works!

**Comment by longouyang** [comment]
Oh - right you are! I've been using http://cheeaun.github.io/hackerweb all this time  -- had no idea the app subdomain worked. Maybe the main button on hackerwebapp.com should link to the app subdomain?

**Comment by cheeaun** [comment]
The app subdomain was initially a workaround for submitting to the Firefox Marketplace. Personally I don't quite like it because "app" is repeated twice in the URL 😜 But yeah @longouyang you can use that 😬

**Comment by longouyang** [comment]
Looks like you got the .app tld, so we're good
